version: '3'

services:
  app:
    build: .
    container_name: rm-api
    ports:
      - 3001:3001
    environment:
      - POSTGRES_USER=railsmentor
      - POSTGRES_PASSWORD=railsmentor
      - POSTGRES_DB=railsmentor
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: rm-postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=railsmentor
      - POSTGRES_PASSWORD=railsmentor
      - POSTGRES_DB=railsmentor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
